name: url-shortener
version: 0.1.0.0
github: "GooeyTuxedo/url-shortener"
license: MIT
author: "MrTuxedo"
maintainer: "dev@based.consulting"
copyright: "2025 MrTuxedo"

description: A URL shortener web application written in Haskell

dependencies:
  - base
  - aeson
  - base64-bytestring
  - bytestring
  - containers
  - cryptonite
  - envparse
  - http-types
  - monad-logger
  - mtl
  - persistent
  - persistent-postgresql
  - persistent-template
  - random
  - resource-pool
  - servant
  - servant-server
  - text
  - time
  - transformers
  - uuid
  - wai
  - wai-cors
  - wai-extra
  - wai-logger
  - warp

library:
  source-dirs: src

executables:
  url-shortener-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - url-shortener

tests:
  url-shortener-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - url-shortener
      - hspec
      - servant-client
      - http-client
      - http-client-tls