resolver: lts-20.26

packages:
- .

extra-deps:
- servant-0.19.1
- servant-server-0.19.2

# For development, we disable tests and benchmarks to speed up builds
flags:
  url-shortener:
    dev: true

# Ensure that GHC includes debugging info
ghc-options:
  "$locals": -fhide-source-paths