apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: url-shortener
  namespace: argo
  annotations:
    # Define which images to track and update
    argocd-image-updater.argoproj.io/image-list: ghcr.io/gooeytuxedo/url-shortener-backend:~v,ghcr.io/gooeytuxedo/url-shortener-frontend:~v
    
    # Set update strategy to semver (will use semantic versioning for tags)
    argocd-image-updater.argoproj.io/ghcr.io/gooeytuxedo/url-shortener-backend.update-strategy: semver
    argocd-image-updater.argoproj.io/ghcr.io/gooeytuxedo/url-shortener-frontend.update-strategy: semver
    
    # Allow using tags like v1.2.3 or other tag formats
    argocd-image-updater.argoproj.io/ghcr.io/gooeytuxedo/url-shortener-backend.tag-match: regexp:^v?(.*)$
    argocd-image-updater.argoproj.io/ghcr.io/gooeytuxedo/url-shortener-frontend.tag-match: regexp:^v?(.*)$
    
    # Specify which k8s objects contain the image specifications
    argocd-image-updater.argoproj.io/ghcr.io/gooeytuxedo/url-shortener-backend.image-name: ghcr.io/gooeytuxedo/url-shortener-backend
    argocd-image-updater.argoproj.io/ghcr.io/gooeytuxedo/url-shortener-backend.kubernetes.deployment-name: url-shortener-backend
    
    argocd-image-updater.argoproj.io/ghcr.io/gooeytuxedo/url-shortener-frontend.image-name: ghcr.io/gooeytuxedo/url-shortener-frontend
    argocd-image-updater.argoproj.io/ghcr.io/gooeytuxedo/url-shortener-frontend.kubernetes.deployment-name: url-shortener-frontend
    
    # Write changes back to Git (GitOps way)
    argocd-image-updater.argoproj.io/write-back-method: git
    
    # Git repository details for write-back
    argocd-image-updater.argoproj.io/git-repository: https://github.com/gooeytuxedo/url-shortener.git
    argocd-image-updater.argoproj.io/git-branch: main
    
    # Path within the repo where kubernetes manifests live
    argocd-image-updater.argoproj.io/git-path: kubernetes
    
    # Specify the secret that contains GitHub credentials
    argocd-image-updater.argoproj.io/git-credentials-secret: argocd-image-updater-github-credentials
spec:
  project: default
  source:
    repoURL: https://github.com/gooeytuxedo/url-shortener.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: url-shortener
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m