apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: url-shortener-cert
  namespace: url-shortener
spec:
  secretName: url-shortener-tls
  issuerRef:
    name: civo
    kind: ClusterIssuer
  dnsNames:
    - short.based.consulting