apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: url-shortener
  namespace: url-shortener
spec:
  entryPoints:
    - websecure
  routes:
    # API routes
    - match: Host(`short.based.consulting`) && PathPrefix(`/api`)
      kind: Rule
      priority: 200
      services:
        - name: url-shortener-backend
          port: 80
          
    # Short URL redirect routes
    - match: Host(`short.based.consulting`) && PathPrefix(`/`) && !PathPrefix(`/api`) && !PathPrefix(`/static`) && !Path(`/`)
      kind: Rule
      priority: 100
      services:
        - name: url-shortener-backend
          port: 80
          
    # Frontend routes (lowest priority, catches everything else)
    - match: Host(`short.based.consulting`) && PathPrefix(`/`)
      kind: Rule
      priority: 10
      services:
        - name: url-shortener-frontend
          port: 80
      middlewares:
        - name: url-shortener-compress
        - name: url-shortener-spa
  tls:
    secretName: url-shortener-tls